fix to restore original formatting

diff --git a/vault b/vault
--- a/vault
+++ b/vault
@@ -30,22 +30,22 @@ usage()
 cat <<EOF
 
 vault simplifies encryption and decryption of files to a vault.
-
+ 
 Usage: $(basename $0) [OPTIONS] filename(s)
 
-	-d       Decrypts the file to the vault and optionally makes
-					 an index to re-encrypt it and copy it back to its
-		 original location.
-	-e       Re-encrypt indexed files in the vault and copy them
-					 to their original location.
-	-p       Path of the vault. Deafults to \$VAULT if set, other-
-					 wise \$HOME/vault
-	-k       GPG key to use to encrypt the files. If not provided
-					 uses \$VAULT_KEY (if set) or the gpg option
-		 --default-recipient-self.
-	-q       Run non-interactively (automatically overwrites)
-	-v	   Print the version
-	-h       Print this help message
+  -d       Decrypts the file to the vault and optionally makes 
+           an index to re-encrypt it and copy it back to its
+	   original location.
+  -e       Re-encrypt indexed files in the vault and copy them
+           to their original location.
+  -p       Path of the vault. Deafults to \$VAULT if set, other-
+           wise \$HOME/vault
+  -k       GPG key to use to encrypt the files. If not provided
+           uses \$VAULT_KEY (if set) or the gpg option
+	   --default-recipient-self.
+  -q       Run non-interactively (automatically overwrites)
+  -v	   Print the version
+  -h       Print this help message
 
 EOF
 }
@@ -56,17 +56,17 @@ QUIET=""
 OPTIND=1
 
 while getopts "hqedk:p:v" opt; do
-		case "$opt" in
-				h)
-								usage
+    case "$opt" in
+        h)
+                usage
 		exit 0
-								;;
+                ;;
 	e)
 		ENCRYPT=1
 		;;
 	d)
-								DECRYPT=1
-								;;
+                DECRYPT=1
+                ;;
 	k)
 		VAULT_KEY=$OPTARG
 		;;
@@ -80,10 +80,10 @@ while getopts "hqedk:p:v" opt; do
 		exit 0
 		;;
 	*)
-					echo "Invalid option: -$OPTARG" >&2
-					exit 1
-					;;
-		esac
+      		echo "Invalid option: -$OPTARG" >&2
+      		exit 1
+      		;;
+    esac
 done
 
 shift $((OPTIND-1))
@@ -153,7 +153,7 @@ decrypt()
 	# Index file
 	INDEX="$(dirname "${OUT}")/.$(basename "${OUT}").vaultindex"
 
-	# Check if $OUT exists
+	# Check if $OUT exists	
 	if [[ -f "${OUT}" ]]; then
 		if [[ ! -f "${INDEX}" ]]; then
 			echo "There is already a file named '$(basename "${OUT}")' in the vault."
@@ -164,7 +164,7 @@ decrypt()
 			read -p "Do you want to overwrite it? (Y/n) " yn
 			case $yn in
 			[Nn]* ) return 0;;
-			* ) break;;
+			* ) break;; 
 			esac
 		done
 	fi
@@ -187,7 +187,7 @@ decrypt()
 		case $yn in
 		[1] ) rm $OUT; return 0;;
 		[3] ) return 0;;
-		* ) break ;;
+		* ) break ;; 
 		esac
 	done
 	# Make an index file in vault
@@ -226,7 +226,7 @@ encrypt(){
 			echo -e "\tError parsing ${index}"
 			break
 		fi
-
+		
 		if [[ -f "${ORIG_FILE}" ]]; then
 			ORIG_HASH=$($GPG --print-md --with-colons sha1 "${ORIG_FILE}")
 		else
@@ -239,7 +239,7 @@ encrypt(){
 		if [[ -f "${ORIG_FILE}" && "${HASH}" != "${ORIG_HASH}" ]]; then
 			echo -e "\t## The original file has been modified after decryption! ##"
 		fi
-
+		
 		if [[ -f "${ORIG_FILE}" ]]; then
 			while $QUIET; do
 			echo -e "\tDo you want to overwrite ${ORIG_FILE}?(Y/n) "
@@ -247,18 +247,18 @@ encrypt(){
 				case $yn in
 				[yY]* ) break ;;
 				[Nn]* ) break 2;;
-				* ) break ;;
+				* ) break ;; 
 				esac
 			done
 		fi
-		$GPG --encrypt $RECIPIENT --batch --yes --output "${ORIG_FILE}" "${DEC_FILE}"
+		$GPG --encrypt $RECIPIENT --batch --yes --output "${ORIG_FILE}" "${DEC_FILE}" 
 		while $QUIET; do
 		echo -e "\tDo you want to delete the unencrypted file ${DEC_FILE} and its index?(Y/n) "
 			read -p "" yn
 			case $yn in
 			[yY]* ) break ;;
 			[Nn]* ) break 2;;
-			* ) break ;;
+			* ) break ;; 
 			esac
 		done
 		rm "${DEC_FILE}"
